# Generated by Django 4.0.2 on 2022-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=200)),
                ('orderQuantity', models.IntegerField()),
                ('orderManager', models.CharField(max_length=200)),
                ('orderDate', models.DateTimeField(verbose_name='date published')),
                ('orderStaus', models.CharField(choices=[('W REALIZACJI', 'W REALIZACJI'), ('NOWE ZLECENIE', 'NOWE ZLECENIE'), ('ZAKOŃCZONO', 'ZAKOŃCZONO'), ('BŁĘDY W ZLECENIU', 'BŁĘDY W ZLECENIU')], default='NOWE ZLECENIE', max_length=50, verbose_name='Status wykonania')),
                ('orderNotes', models.CharField(max_length=200)),
            ],
        ),
    ]
