# Generated by Django 4.0.2 on 2022-10-06 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemMaterial', models.CharField(max_length=200, verbose_name='Materiał')),
                ('itemQuantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Ilość sztuk')),
                ('itemDimmension1', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Wymiar 1 (mm)')),
                ('itemBander', models.CharField(choices=[('BEZ OKLEJANIA', 'BEZ OKLEJANIA'), ('OKLEJANIE 1 STR', 'OKLEJANIE 1 STR'), ('OKLEJANIE 2 STR', 'OKLEJANIE 2 STR')], default='BEZ OKLEJANIA', max_length=200, verbose_name='Oklejanie wymiaru 1')),
                ('itemDimmension2', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Wymiar 2 (mm)')),
                ('itemBander2', models.CharField(choices=[('BEZ OKLEJANIA', 'BEZ OKLEJANIA'), ('OKLEJANIE 1 STR', 'OKLEJANIE 1 STR'), ('OKLEJANIE 2 STR', 'OKLEJANIE 2 STR')], default='BEZ OKLEJANIA', max_length=200, verbose_name='Oklejanie wymiaru 2')),
                ('itemName', models.CharField(max_length=200, verbose_name='Nazwa części')),
                ('isDone', models.BooleanField(default=False, verbose_name='Zrealizowane')),
            ],
            options={
                'verbose_name': 'Element do cięcia',
                'verbose_name_plural': 'Elementy do cięcia',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=14, unique=True, verbose_name='Numer zlecenia')),
                ('orderName', models.CharField(max_length=30, verbose_name='Nazwa zlecenia')),
                ('orderQuantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Nakład')),
                ('orderDate', models.DateTimeField(auto_now=True, verbose_name='Data dodania')),
                ('isDone', models.BooleanField(default=False, verbose_name='Zrealizowane')),
                ('orderNotes', models.CharField(blank=True, default='Brak', max_length=30, verbose_name='Uwagi')),
                ('finishedBy', models.CharField(blank=True, default='Brak', max_length=30, verbose_name='Zrealizowane przez')),
                ('finishedDate', models.DateTimeField(auto_now=True, verbose_name='Data zakończenia')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
    ]
