# Generated by Django 4.0.2 on 2022-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_orderdate_alter_order_orderstaus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderStaus',
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('W REALIZACJI', 'W REALIZACJI'), ('NOWE ZLECENIE', 'NOWE ZLECENIE'), ('ZAKOŃCZONO', 'ZAKOŃCZONO'), ('BŁĘDY W ZLECENIU', 'BŁĘDY W ZLECENIU')], default='NOWE ZLECENIE', max_length=50, verbose_name='Status wykonania'),
        ),
    ]
