# Generated by Django 4.0.2 on 2022-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Numer zlecenia'),
        ),
    ]
