# Generated by Django 4.0.2 on 2022-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=200, verbose_name='Numer zlecenia'),
        ),
    ]
