<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-05 20:49
=======
# Generated by Django 4.0.2 on 2022-03-05 21:07
>>>>>>> 222bebadf7bf6db6667e903a28cf4f5adeda5ca3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=200, verbose_name='Numer zlecenia'),
        ),
    ]
