# Generated by Django 4.0.2 on 2022-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_ordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderStatus',
        ),
        migrations.AddField(
            model_name='order',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Zrealizowane'),
        ),
    ]
