# Generated by Django 4.0.2 on 2022-03-08 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_orderstatus_order_isdone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Element do cięcia', 'verbose_name_plural': 'Elementy do cięcia'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zlecenie', 'verbose_name_plural': 'Zlecenia'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPartName',
            new_name='itemName',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderManager',
            field=models.CharField(max_length=30, verbose_name='Kierownik zlecenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderName',
            field=models.CharField(max_length=30, verbose_name='Nazwa zlecenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNotes',
            field=models.CharField(blank=True, default='Brak', max_length=30, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=30, verbose_name='Numer zlecenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Nakład'),
        ),
    ]
