# Generated by Django 4.0.2 on 2022-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_item_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemBander2',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemBander',
            field=models.CharField(choices=[('BEZ OKLEJANIA', 'BEZ OKLEJANIA'), ('OKLEJANIE 1 STR', 'OKLEJANIE 1 STR'), ('OKLEJANIE 2 STR', 'OKLEJANIE 2 STR')], default='BEZ OKLEJANIA', max_length=200, verbose_name='Oklejanie 2'),
        ),
    ]
