# Generated by Django 4.0.2 on 2022-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_item_itembander2_alter_item_itembander'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemBander2',
            field=models.CharField(choices=[('BEZ OKLEJANIA', 'BEZ OKLEJANIA'), ('OKLEJANIE 1 STR', 'OKLEJANIE 1 STR'), ('OKLEJANIE 2 STR', 'OKLEJANIE 2 STR')], default='BEZ OKLEJANIA', max_length=200, verbose_name='Oklejanie 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemBander',
            field=models.CharField(choices=[('BEZ OKLEJANIA', 'BEZ OKLEJANIA'), ('OKLEJANIE 1 STR', 'OKLEJANIE 1 STR'), ('OKLEJANIE 2 STR', 'OKLEJANIE 2 STR')], default='BEZ OKLEJANIA', max_length=200, verbose_name='Oklejanie 1'),
        ),
    ]
