# Generated by Django 4.0.2 on 2022-03-22 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_alter_item_itembander_alter_item_itembander2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderManager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik zlecenia'),
        ),
    ]
