# Generated by Django 4.0.2 on 2022-03-25 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_alter_order_ordermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDimmension1',
            field=models.IntegerField(verbose_name='Wymiar 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDimmension2',
            field=models.IntegerField(verbose_name='Wymiar 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik zlecenia'),
        ),
    ]
