# Generated by Django 4.0.2 on 2022-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_item_itemdimmension1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDimmension1',
            field=models.FloatField(verbose_name='Wymiar 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDimmension2',
            field=models.FloatField(verbose_name='Wymiar 2 (mm)'),
        ),
    ]
