# Generated by Django 4.0.2 on 2022-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_item_itemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemMaterial',
            field=models.CharField(max_length=200, verbose_name='Materiał'),
        ),
    ]
