# Generated by Django 4.0.2 on 2022-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_item_itemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=30, unique=True, verbose_name='Numer zlecenia'),
        ),
    ]
