# Generated by Django 4.0.2 on 2022-03-31 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0018_alter_item_itemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik zlecenia'),
        ),
    ]
