# Generated by Django 4.0.2 on 2022-04-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_ordermanager'),
        ('orders', '0019_alter_order_ordernumber'),
    ]

    operations = [
    ]
