# Generated by Django 4.0.2 on 2022-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_merge_20220401_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Zrealizowane'),
        ),
    ]
