# Generated by Django 4.0.2 on 2022-04-07 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_finishedby_order_finisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDimmension1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Wymiar 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDimmension2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Wymiar 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Ilość sztuk'),
        ),
    ]
