# Generated by Django 4.0.2 on 2022-03-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_operator',
        ),
    ]
